const ChatConstants = {
    UPDATE_MESSAGES: '[UPDATE_MESSAGES]',
    SEND_MESSAGE: '[SEND_MESSAGE]',
    MESSAGE_SENDED: '[MESSAGE_SENDED]',
    UPDATE_CHAT_MEMBERS: '[UPDATE_CHAT_MEMBERS]',
    OPEN_MEMBERS_MODAL: '[OPEN_MEMBERS_MODAL]',
    CLOSE_MEMBERS_MODAL: '[CLOSE_MEMBERS_MODAL]',
    ADD_MEMBER: '[ADD_MEMBER]',
    MEMBER_ADDED: '[MEMBER_ADDED]',
    REMOVE_MEMBER: '[REMOVE_MEMBER]',
    MEMBER_REMOVED: '[MEMBER_REMOVED]',
}

export default ChatConstants