const DashboardConstants = {
    CREATE_CHAT: '[CREATE_CHAT]',
    ADD_NEW_CHAT: '[ADD_NEW_CHAT]',
    WATCH_CHATS: '[WATCH_CHATS]',
    UPDATE_CHATS: '[UPDATE_CHATS]',
    CHAT_SELECTED: '[CHAT_SELECTED]',
    UPDATE_CHATS_ADMIN: '[UPDATE_CHATS_ADMIN]',
    ADD_NEW_NOTIFICATION: '[ADD_NEW_NOTIFICATION]',
    REMOVE_NOTIFICATION: '[REMOVE_NOTIFICATION]',
    UPDATE_NOTIFICATIONS: '[UPDATE_NOTIFICATIONS]',
}

export default DashboardConstants